<?xml version="1.0" encoding="UTF-8"?>
2017-09-30 13:55:54,275 - log.py[line:88] - INFO:   run 正确登录.
2017-09-30 13:55:54,275 - remote_connection.py[line:478] - DEBUG: POST http://127.0.0.1:4723/wd/hub/session/ba5564e8-6a75-495d-bbbe-0c510807cbea/context {"sessionId": "ba5564e8-6a75-495d-bbbe-0c510807cbea", "name": "WEBVIEW"}
2017-09-30 13:55:54,336 - remote_connection.py[line:565] - DEBUG: Finished Request
2017-09-30 13:55:54,336 - creat_case.py[line:116] - ERROR: Message: No such context found.

2017-09-30 13:55:54,338 - remote_connection.py[line:478] - DEBUG: GET http://127.0.0.1:4723/wd/hub/session/ba5564e8-6a75-495d-bbbe-0c510807cbea/screenshot {"sessionId": "ba5564e8-6a75-495d-bbbe-0c510807cbea"}
